(() => {
  const inrDestination = [
    ["Container Protect Essential", "Container", "INR", 3800],
    ["Documentation fee — Destination", "Bill of Lading", "INR", 6710],
    ["Terminal Handling Service — Destination", "Container", "INR", 15750],
  ];
  const thbDestination = [
    ["Container Protect Essential", "Container", "THB", 850],
    ["Documentation fee — Destination", "Bill of Lading", "THB", 1500],
  ];
  const usdDestination = [
    ["Container Protect Essential", "Container", "USD", 40],
    ["Documentation fee — Destination", "Bill of Lading", "USD", 65],
    ["Terminal Handling Service — Destination", "Container", "USD", 165],
  ];

  function maerskRate(id, destination, basicFreight, bunker, destinationCharges, sailing) {
    return {
      id,
      carrier: "Maersk",
      service: "Quay-to-quay",
      destinations: [destination],
      origins: ["Felixstowe", "Southampton"],
      equipment: "40HC",
      materials: ["Paper", "Metal", "Tyres"],
      sourceFile: "MAERSK_CONTRACT_299077037_JUL.xlsx",
      validity: "to 31 Jul",
      sailing,
      freetime: "14d detention + 2d demurrage incl.",
      origin: [
        ["Export Intermodal Fuel Fee", "Percent", "GBP", 0],
        ["Export Service", "Container", "USD", 0],
      ],
      freight: [
        ["Basic Ocean Freight", "Container", "USD", basicFreight],
        ["Emergency Bunker Surcharge", "Container", "USD", bunker],
      ],
      destination: destinationCharges,
      zeroChargeCount: 5,
    };
  }

  function mscRate(id, destination, basicFreight, bunker, destinationCharges, sailing) {
    return {
      id,
      carrier: "MSC",
      service: "Door-to-quay",
      collections: ["Abbots Bromley", "Manchester"],
      destinations: [destination],
      origins: ["Felixstowe", "Liverpool"],
      equipment: "40HC",
      materials: ["Paper", "Metal", "Tyres"],
      sourceFile: "MSC_FAR_EAST_AUG.xlsx",
      validity: "to 31 Aug",
      sailing,
      freetime: "10d detention incl.",
      origin: [
        ["Terminal Handling — Origin", "Container", "GBP", 185],
        ["Export Service", "Container", "GBP", 45],
      ],
      freight: [
        ["Basic Ocean Freight", "Container", "USD", basicFreight],
        ["Bunker Adjustment Factor", "Container", "USD", bunker],
      ],
      destination: destinationCharges,
      zeroChargeCount: 0,
    };
  }

  function hapagRate(id, destination, basicFreight, bunker, destinationCharges, sailing) {
    return {
      id,
      carrier: "Hapag-Lloyd",
      service: "Door-to-quay",
      collections: ["Abbots Bromley", "Manchester"],
      destinations: [destination],
      origins: ["Felixstowe", "Southampton"],
      equipment: "40HC",
      materials: ["Paper", "Metal", "Tyres"],
      sourceFile: "HAPAG_FAR_EAST_RATES.xlsx",
      validity: "to 31 Aug",
      sailing,
      freetime: "7d detention + 3d demurrage incl.",
      origin: [
        ["Terminal Handling — Origin", "Container", "GBP", 192],
        ["Documentation fee — Origin", "Bill of Lading", "GBP", 55],
      ],
      freight: [
        ["Basic Ocean Freight", "Container", "USD", basicFreight],
        ["Bunker Adjustment Factor", "Container", "USD", bunker],
      ],
      destination: destinationCharges,
      zeroChargeCount: 0,
    };
  }

  window.RATE_DESK_DEMO = Object.freeze({
    sources: [
      {
        key: "maersk-contract",
        provider: "Maersk",
        service: "Quay-to-quay",
        cadence: "monthly",
        current: {
          id: "demo-maersk-quay-jul",
          file: "maersk_contract_299077037_jul.xlsx",
          uploaded: "3 Jul, 09:20",
          validFrom: "2026-07-01",
          validTo: "2026-07-31",
          lanes: 28,
          status: "current",
          summaryKey: "maersk-contract",
        },
        archived: [],
      },
      {
        key: "maersk-door",
        provider: "Maersk",
        service: "Door-to-quay",
        cadence: "monthly",
        current: {
          id: "demo-maersk-door-jul",
          file: "maersk_door_299077037_jul.xlsx",
          uploaded: "3 Jul, 09:24",
          validFrom: "2026-07-01",
          validTo: "2026-07-31",
          lanes: 18,
          status: "current",
          summaryKey: "maersk-door",
        },
        archived: [],
      },
      {
        key: "msc-inline",
        provider: "MSC",
        service: "Door-to-quay",
        cadence: "monthly",
        current: {
          id: "demo-msc-aug",
          file: "msc_far_east_aug.xlsx",
          uploaded: "14 Jul, 08:05",
          validFrom: "2026-08-01",
          validTo: "2026-08-31",
          lanes: 42,
          status: "current",
          summaryKey: "msc-inline",
        },
        archived: [{
          id: "demo-msc-jan",
          file: "msc_far_east_jan.xlsx",
          uploaded: "6 Jan, 11:40",
          validFrom: "2026-01-01",
          validTo: "2026-01-31",
          lanes: 39,
          status: "archived",
          summaryKey: "msc-inline",
        }],
      },
      {
        key: "hapag-door",
        provider: "Hapag-Lloyd",
        service: "Door-to-quay",
        cadence: "monthly",
        current: {
          id: "demo-hapag-aug",
          file: "hapag_far_east_rates.xlsx",
          uploaded: "11 Jul, 16:12",
          validFrom: "2026-08-01",
          validTo: "2026-08-31",
          lanes: 24,
          status: "current",
          summaryKey: "hapag-door",
        },
        archived: [],
      },
      {
        key: "haulage-q2",
        provider: "UK Inland Haulage",
        service: "Export · all UK POLs",
        cadence: "quarterly",
        current: {
          id: "demo-haulage-q2",
          file: "uk_haulage_export_all_pols_q2_2026.xlsx",
          uploaded: "1 Apr, 14:02",
          validFrom: "2026-04-01",
          validTo: "2026-06-30",
          lanes: 1636,
          status: "current",
          summaryKey: "haulage-q2",
        },
        archived: [],
      },
    ],
    parseSummaries: {
      "maersk-contract": {
        validity: "1 Aug → 31 Aug 2026",
        validFrom: "2026-08-01",
        validTo: "2026-08-31",
        lanes: 28,
        skipped: "1 row skipped (no rate)",
        previousLabel: "Jul",
        mappedCount: 12,
        unmatchedCount: 0,
        buckets: [
          { label: "origin", count: 2 },
          { label: "freight", count: 7 },
          { label: "destination", count: 3 },
        ],
        note: "5 freight charges priced at 0 (congestion, freetime extension, contingency, peak season).",
        deltaLabel: "All-in USD vs. previous sheet",
        differences: [
          ["Felixstowe → Mundra", 1174, 1152],
          ["Felixstowe → Laem Chabang", 571, 571],
          ["Felixstowe → Nhava Sheva", 1133, 1161],
          ["Southampton → Jakarta", 840, 826],
        ],
        remaining: "+ 24 more lanes within ±$10.",
      },
      "maersk-door": {
        validity: "1 Aug → 31 Aug 2026",
        validFrom: "2026-08-01",
        validTo: "2026-08-31",
        lanes: 18,
        skipped: "0 rows skipped",
        previousLabel: "Jul",
        mappedCount: 7,
        unmatchedCount: 0,
        buckets: [
          { label: "origin", count: 2 },
          { label: "freight", count: 2 },
          { label: "destination", count: 3 },
        ],
        note: "Inland haulage is included in Basic Ocean Freight — not a separate charge.",
        deltaLabel: "All-in USD vs. previous sheet",
        differences: [
          ["Abbots Bromley → Laem Chabang", 751, 751],
          ["Abbots Bromley → Mundra", 1354, 1332],
          ["Aberdeen → Nhava Sheva", 2418, 2446],
        ],
        remaining: "+ 15 more door lanes.",
      },
      "msc-inline": {
        validity: "1 Sep → 30 Sep 2026",
        validFrom: "2026-09-01",
        validTo: "2026-09-30",
        lanes: 42,
        skipped: "3 rows skipped (no rate)",
        previousLabel: "Aug",
        mappedCount: 12,
        unmatchedCount: 0,
        buckets: [
          { label: "origin", count: 3 },
          { label: "freight", count: 5 },
          { label: "destination", count: 4 },
        ],
        note: "Bunker Adjustment Factor read as freight, not a separate surcharge.",
        deltaLabel: "All-in USD vs. previous sheet",
        differences: [
          ["Felixstowe → Laem Chabang", 490, 478],
          ["Liverpool → Jakarta", 600, 612],
          ["Felixstowe → Nhava Sheva", 830, 830],
        ],
        remaining: "+ 39 more lanes within ±$15.",
      },
      "hapag-door": {
        validity: "1 Sep → 30 Sep 2026",
        validFrom: "2026-09-01",
        validTo: "2026-09-30",
        lanes: 24,
        skipped: "0 rows skipped",
        previousLabel: "Aug",
        mappedCount: 9,
        unmatchedCount: 1,
        buckets: [
          { label: "origin", count: 2 },
          { label: "freight", count: 4 },
          { label: "destination", count: 3 },
        ],
        note: "ISPS Security Fee not recognised — classify it before these rates go live.",
        deltaLabel: "All-in USD vs. previous sheet",
        differences: [
          ["Felixstowe → Laem Chabang", 530, 545],
          ["Southampton → Mundra", 830, 812],
          ["Felixstowe → Nhava Sheva", 880, 880],
        ],
        remaining: "+ 21 more lanes.",
      },
      "haulage-q2": {
        validity: "1 Jul → 30 Sep 2026",
        validFrom: "2026-07-01",
        validTo: "2026-09-30",
        lanes: 1636,
        skipped: "1,130 cells at £0 — read as no rate (POA), not free haulage",
        previousLabel: "Q2",
        mappedCount: 1,
        unmatchedCount: 0,
        buckets: [{ label: "inland", count: 1 }],
        note: "£0 cells mean the haulier does not serve that corridor — Quote shows POA.",
        deltaLabel: "Haulage rate £/container",
        currencySymbol: "£",
        differences: [
          ["Abbots Bromley → Felixstowe", 140.14, 143.9],
          ["Aberdare → Felixstowe", 369.25, 369.25],
          ["Aberdeen → Liverpool", 1280.8, 1298.4],
        ],
        remaining: "+ 1,633 more town/POL pairs.",
      },
    },
    quote: {
      fx: { USD: 1, GBP: 1.29, INR: 0.0104, THB: 0.0302 },
      haulage: {
        "Abbots Bromley": { Felixstowe: 140.14, Southampton: 105.21, Liverpool: 279.58 },
        Aldeburgh: { Felixstowe: 0, Southampton: 184.84, Liverpool: 990.22 },
        Aberdare: { Felixstowe: 369.25, Southampton: 246.31, Liverpool: 702.88 },
        Aberdeen: { Felixstowe: 996.06, Southampton: 1050.54, Liverpool: 1280.8 },
        Accrington: { Felixstowe: 138.07, Southampton: 138.07, Liverpool: 0 },
        Aintree: { Felixstowe: 304.55, Southampton: 284.99, Liverpool: 0 },
        Alfreton: { Felixstowe: 175.06, Southampton: 184.84, Liverpool: 306.13 },
        Manchester: { Felixstowe: 84.99, Southampton: 59.84, Liverpool: 0 },
      },
      doorUplift: {
        "Abbots Bromley": 180,
        Aldeburgh: 95,
        Aberdare: 476,
        Aberdeen: 1285,
        Accrington: 178,
        Aintree: 394,
        Alfreton: 226,
        Manchester: 118,
      },
      rates: [
        maerskRate("maersk-laem-chabang", "Laem Chabang", 450, 50, thbDestination, "Dep 20 Jul 01:00 · 50d 15h · GDANSK EXPRESS / 629E · gate-in 20 Jul 23:30"),
        maerskRate("maersk-mundra", "Mundra", 700, 200, inrDestination, "Dep 29 Jul 12:01 · 40d 16h · VANCOUVER EXPRESS / 630E · gate-in 30 Jul 10:30"),
        maerskRate("maersk-nhava-sheva", "Nhava Sheva (JNPT)", 660, 200, inrDestination, "Dep 27 Jul 09:00 · 31d 4h · MAERSK COLOMBO / 512W · gate-in 26 Jul 20:00"),
        maerskRate("maersk-tuticorin", "Tuticorin", 730, 200, inrDestination, "Dep 30 Jul 14:00 · 39d 2h · GJERTRUD MAERSK / 631E · gate-in 29 Jul 22:00"),
        maerskRate("maersk-jakarta", "Jakarta", 520, 50, usdDestination, "Dep 21 Jul 03:00 · 47d 9h · GDANSK EXPRESS / 629E · gate-in 20 Jul 23:30"),
        mscRate("msc-laem-chabang", "Laem Chabang", 395, 95, thbDestination, "Dep 23 Jul 06:00 · 46d 2h · MSC SIXIN / FE428A · gate-in 22 Jul 16:00"),
        mscRate("msc-nhava-sheva", "Nhava Sheva (JNPT)", 690, 140, inrDestination, "Dep 25 Jul 18:00 · 28d 20h · MSC RIFAYA / IN331W · gate-in 24 Jul 20:00"),
        mscRate("msc-jakarta", "Jakarta", 505, 95, usdDestination, "Dep 26 Jul 11:00 · 44d 6h · MSC POH LIN / SE221A · gate-in 25 Jul 18:00"),
        hapagRate("hapag-laem-chabang", "Laem Chabang", 470, 60, thbDestination, "Dep 19 Jul 22:00 · 43d 8h · ESSEN EXPRESS / 118E · gate-in 19 Jul 12:00"),
        hapagRate("hapag-mundra", "Mundra", 655, 175, inrDestination, "Dep 28 Jul 07:00 · 37d 12h · CHICAGO EXPRESS / 041W · gate-in 27 Jul 16:00"),
        hapagRate("hapag-nhava-sheva", "Nhava Sheva (JNPT)", 705, 175, inrDestination, "Dep 24 Jul 16:00 · 33d 6h · BERLIN EXPRESS / 052W · gate-in 23 Jul 20:00"),
      ],
    },
  });
})();
