window.RATE_DESK_DEMO = Object.freeze({
  sources: [
    {
      key: "maersk-contract",
      name: "Maersk Key-to-key",
      cadence: "monthly",
      current: {
        id: "demo-maersk-key-jul",
        file: "maersk_contract_299077037_jul.xlsx",
        uploaded: "3 Jul, 09:20",
        validFrom: "2026-07-01",
        validTo: "2026-07-31",
        lanes: 28,
        status: "current",
        summaryKey: "maersk-contract",
      },
      archived: [],
    },
    {
      key: "maersk-door",
      name: "Maersk Door-to-key",
      cadence: "monthly",
      current: {
        id: "demo-maersk-door-jul",
        file: "maersk_door_299077037_jul.xlsx",
        uploaded: "3 Jul, 09:24",
        validFrom: "2026-07-01",
        validTo: "2026-07-31",
        lanes: 18,
        status: "current",
        summaryKey: "maersk-door",
      },
      archived: [],
    },
    {
      key: "haulage-q2",
      name: "UK Inland Haulage",
      cadence: "quarterly",
      current: {
        id: "demo-haulage-q2",
        file: "uk_haulage_export_all_pols_q2_2026.xlsx",
        uploaded: "1 Apr, 14:02",
        validFrom: "2026-04-01",
        validTo: "2026-06-30",
        lanes: 1636,
        status: "overdue",
        summaryKey: "haulage-q2",
      },
      archived: [],
    },
  ],
  parseSummaries: {
    "maersk-contract": {
      validity: "1 Aug → 31 Aug 2026",
      validFrom: "2026-08-01",
      validTo: "2026-08-31",
      lanes: 28,
      skipped: "1 row skipped (no rate)",
      previousLabel: "Jul",
      mappedCount: 12,
      unmatchedCount: 0,
      buckets: [
        { label: "origin", count: 2 },
        { label: "freight", count: 7 },
        { label: "destination", count: 3 },
      ],
      note: "5 freight charges priced at 0 (congestion, freetime ext, contingency, peak season).",
      deltaLabel: "All-in USD vs. previous sheet",
      differences: [
        ["Felixstowe → Mundra", 1174, 1152],
        ["Felixstowe → Laem Chabang", 571, 571],
        ["Felixstowe → Nhava Sheva", 1133, 1161],
        ["Southampton → Jakarta", 840, 826],
      ],
      remaining: "+ 24 more lanes within ±$10.",
    },
    "maersk-door": {
      validity: "1 Aug → 31 Aug 2026",
      validFrom: "2026-08-01",
      validTo: "2026-08-31",
      lanes: 18,
      skipped: "0 rows skipped",
      previousLabel: "Jul",
      mappedCount: 7,
      unmatchedCount: 0,
      buckets: [
        { label: "origin", count: 2 },
        { label: "freight", count: 2 },
        { label: "destination", count: 3 },
      ],
      note: "Inland haulage is included in Basic Ocean Freight — not a separate charge.",
      deltaLabel: "All-in USD vs. previous sheet",
      differences: [
        ["Abbots Bromley → Laem Chabang", 751, 751],
        ["Abbots Bromley → Mundra", 1354, 1332],
        ["Aberdeen → Nhava Sheva", 2418, 2446],
      ],
      remaining: "+ 15 more door lanes.",
    },
    "haulage-q2": {
      validity: "1 Jul → 30 Sep 2026",
      validFrom: "2026-07-01",
      validTo: "2026-09-30",
      lanes: 1636,
      skipped: "1,130 cells at £0 — read as no rate (POA), not free haulage",
      previousLabel: "Q2",
      mappedCount: 1,
      unmatchedCount: 0,
      buckets: [{ label: "inland", count: 1 }],
      note: "£0 cells mean the haulier does not serve that corridor — Quote shows POA.",
      deltaLabel: "Haulage rate £/container",
      currencySymbol: "£",
      differences: [
        ["Abbots Bromley → Felixstowe", 140.14, 143.9],
        ["Aberdare → Felixstowe", 369.25, 369.25],
        ["Aberdeen → Liverpool", 1280.8, 1298.4],
      ],
      remaining: "+ 1,633 more town/POL pairs.",
    },
  },
  quote: {
    fx: { USD: 1, GBP: 1.29, INR: 0.0104, THB: 0.0302 },
    haulage: {
      "Abbots Bromley": { Felixstowe: 140.14, Southampton: 105.21, Liverpool: 279.58 },
      Aldeburgh: { Felixstowe: 0, Southampton: 184.84, Liverpool: 990.22 },
      Aberdare: { Felixstowe: 369.25, Southampton: 246.31, Liverpool: 702.88 },
      Aberdeen: { Felixstowe: 996.06, Southampton: 1050.54, Liverpool: 1280.8 },
      Accrington: { Felixstowe: 138.07, Southampton: 138.07, Liverpool: 0 },
      Aintree: { Felixstowe: 304.55, Southampton: 284.99, Liverpool: 0 },
      Alfreton: { Felixstowe: 175.06, Southampton: 184.84, Liverpool: 306.13 },
      Manchester: { Felixstowe: 84.99, Southampton: 59.84, Liverpool: 0 },
    },
    doorUplift: {
      "Abbots Bromley": 180,
      Aldeburgh: 95,
      Aberdare: 476,
      Aberdeen: 1285,
      Accrington: 178,
      Aintree: 394,
      Alfreton: 226,
      Manchester: 118,
    },
    rates: [
      {
        id: "contract-laem-chabang",
        destinations: ["Laem Chabang"],
        origins: ["Felixstowe", "Southampton"],
        equipment: "40HC",
        materials: ["Paper", "Metal", "Tyres"],
        sourceFile: "MAERSK_CONTRACT_299077037_JUL.xlsx",
        sourceTag: "KEY",
        validity: "to 31 Jul",
        sailing: "Dep 20 Jul 01:00 · 50d 15h · GDANSK EXPRESS / 629E · gate-in 20 Jul 23:30",
        freetime: "14d detention + 2d demurrage incl.",
        origin: [
          ["Export Intermodal Fuel Fee", "Percent", "GBP", 0],
          ["Export Service", "Container", "USD", 0],
        ],
        freight: [
          ["Basic Ocean Freight", "Container", "USD", 450],
          ["Emergency Bunker Surcharge", "Container", "USD", 50],
        ],
        destination: [
          ["Container Protect Essential", "Container", "THB", 850],
          ["Documentation fee — Destination", "Bill of Lading", "THB", 1500],
        ],
        zeroChargeCount: 5,
      },
      {
        id: "contract-mundra",
        destinations: ["Mundra"],
        origins: ["Felixstowe", "Southampton"],
        equipment: "40HC",
        materials: ["Paper", "Metal", "Tyres"],
        sourceFile: "MAERSK_CONTRACT_299077037_JUL.xlsx",
        sourceTag: "KEY",
        validity: "to 31 Jul",
        sailing: "Dep 29 Jul 12:01 · 40d 16h · VANCOUVER EXPRESS / 630E · gate-in 30 Jul 10:30",
        freetime: "14d detention + 2d demurrage incl.",
        origin: [
          ["Export Intermodal Fuel Fee", "Percent", "GBP", 0],
          ["Export Service", "Container", "USD", 0],
        ],
        freight: [
          ["Basic Ocean Freight", "Container", "USD", 700],
          ["Emergency Bunker Surcharge", "Container", "USD", 200],
        ],
        destination: [
          ["Container Protect Essential", "Container", "INR", 3800],
          ["Documentation fee — Destination", "Bill of Lading", "INR", 6710],
          ["Terminal Handling Service — Destination", "Container", "INR", 15750],
        ],
        zeroChargeCount: 5,
      },
      {
        id: "contract-nhava-sheva",
        destinations: ["Nhava Sheva (JNPT)"],
        origins: ["Felixstowe", "Southampton"],
        equipment: "40HC",
        materials: ["Paper", "Metal", "Tyres"],
        sourceFile: "MAERSK_CONTRACT_299077037_JUL.xlsx",
        sourceTag: "KEY",
        validity: "to 31 Jul",
        sailing: "Dep 27 Jul 09:00 · 31d 4h · MAERSK COLOMBO / 512W · gate-in 26 Jul 20:00",
        freetime: "14d detention + 2d demurrage incl.",
        origin: [
          ["Export Intermodal Fuel Fee", "Percent", "GBP", 0],
          ["Export Service", "Container", "USD", 0],
        ],
        freight: [
          ["Basic Ocean Freight", "Container", "USD", 660],
          ["Emergency Bunker Surcharge", "Container", "USD", 200],
        ],
        destination: [
          ["Container Protect Essential", "Container", "INR", 3800],
          ["Documentation fee — Destination", "Bill of Lading", "INR", 6710],
          ["Terminal Handling Service — Destination", "Container", "INR", 15750],
        ],
        zeroChargeCount: 5,
      },
      {
        id: "contract-tuticorin",
        destinations: ["Tuticorin"],
        origins: ["Felixstowe", "Southampton"],
        equipment: "40HC",
        materials: ["Paper", "Metal", "Tyres"],
        sourceFile: "MAERSK_CONTRACT_299077037_JUL.xlsx",
        sourceTag: "KEY",
        validity: "to 31 Jul",
        sailing: "Dep 30 Jul 14:00 · 39d 2h · GJERTRUD MAERSK / 631E · gate-in 29 Jul 22:00",
        freetime: "14d detention + 2d demurrage incl.",
        origin: [
          ["Export Intermodal Fuel Fee", "Percent", "GBP", 0],
          ["Export Service", "Container", "USD", 0],
        ],
        freight: [
          ["Basic Ocean Freight", "Container", "USD", 730],
          ["Emergency Bunker Surcharge", "Container", "USD", 200],
        ],
        destination: [
          ["Container Protect Essential", "Container", "INR", 3800],
          ["Documentation fee — Destination", "Bill of Lading", "INR", 6710],
          ["Terminal Handling Service — Destination", "Container", "INR", 15750],
        ],
        zeroChargeCount: 5,
      },
      {
        id: "contract-jakarta",
        destinations: ["Jakarta"],
        origins: ["Felixstowe", "Southampton"],
        equipment: "40HC",
        materials: ["Paper", "Metal", "Tyres"],
        sourceFile: "MAERSK_CONTRACT_299077037_JUL.xlsx",
        sourceTag: "KEY",
        validity: "to 31 Jul",
        sailing: "Dep 21 Jul 03:00 · 47d 9h · GDANSK EXPRESS / 629E · gate-in 20 Jul 23:30",
        freetime: "14d detention + 2d demurrage incl.",
        origin: [
          ["Export Intermodal Fuel Fee", "Percent", "GBP", 0],
          ["Export Service", "Container", "USD", 0],
        ],
        freight: [
          ["Basic Ocean Freight", "Container", "USD", 520],
          ["Emergency Bunker Surcharge", "Container", "USD", 50],
        ],
        destination: [
          ["Container Protect Essential", "Container", "USD", 40],
          ["Documentation fee — Destination", "Bill of Lading", "USD", 65],
          ["Terminal Handling Service — Destination", "Container", "USD", 165],
        ],
        zeroChargeCount: 5,
      },
    ],
  },
});
